### PR TITLE
Handle indirect repos - set tags to empty.

### PR DESCRIPTION
**Pull request by resuscv**
I've updated the code to set tags to NULL/empty when the repo is indirect.

I've done this by looking at the sub-directories for the file - if the highest sub-directory is `.git` then we must be in an indirect repo.

i.e. an indirect filename looks something like:

```
/home/me/annex-photos/.git/annex/objects/gX/Z3/SHA256E-<blah>.jpg/SHA256E-<blah>.jpg
```

So the top sub-directory here is `.git`

### CODE REVIEW

**Comment by TobiasTheViking** [comment]
Did you actually run a test of this on a indirect repository?

"Tags will _always_ be NULL for indirect repos" <- do you know that to be true? or just assume

" if (len(tags) > 0) and (tags[len(tags) - 1] == ".git"): " <- looks like it is taking the last element and comparing it to .git, not the first. And can you always be sure the first would be .git? Couldn't the path somehow come in as an absolute path(ie, /home/user/annex/,git)

**Comment by TobiasTheViking** [comment]
Oh, and please merge your code with trunk, it's out of sync.

**Comment by resuscv** [comment]
Absolutely confident about (and tested!) the

```
if (len(tags) > 0) and (tags[len(tags) - 1] == ".git"):
```

the list `tags` is created by appending the last element of the path and iterating.  So the last element of `tags` is the first element of the directory string.

The absolute path is a bit of an issues - but only if `GIT_TOP_LEVEL` is not defined.

I'll merge into your master and then resubmit the pull.

**Comment by TobiasTheViking** [comment]
Sounds good. Thanks for the patch :)

**Pull request closed without merging**
